version: "3.9"

services:
    
    machine:
        build:
            context: $HOME/repo/node_course/auth_node/
            dockerfile: $HOME/repo/node_course/local_deploy/Dockerfile_node
        container_name: api_node
        volumes:
            - $HOME/repo/node_course/auth_node/:/code
            - /code/node_modules
        ports:
            - "4000:4000"
        env_file:
            - $HOME/repo/node_course/auth_node/.env.dev
        depends_on:
            - db

    db:
        build:
            context: .
            dockerfile: Dockerfile_postgres
        container_name: postgres
        restart: always
        env_file: 
            - .env.dev.db
        volumes:
            - ../data:/var/lib/postgresql/data
        ports:
            - "5005:5432"    

    angularfrontend:
        build:
            context: $HOME/repo/node_course/auth_angular/
            dockerfile: $HOME/repo/node_course/local_deploy/Dockerfile_angular
        container_name: angular
        volumes:
            - $HOME/repo/node_course/auth_angular/:/code
            - /code/node_modules
        ports:
            - "8081:4200"
        depends_on:
            - graphql_proxy
        links:
            - graphql_proxy

    graphql_proxy:
        build:
            context: $HOME/repo/node_course/auth_graphql/
            dockerfile: $HOME/repo/node_course/local_deploy/Dockerfile_python
        container_name: graphql
        volumes:
            - $HOME/repo/node_course/auth_graphql/:/app
        ports:
            - "8082:5000"
        env_file:
            - $HOME/repo/node_course/auth_graphql/.env.dev
        depends_on:
            - machine
        links:
            - machine
