FROM python:3.7

WORKDIR /app

# RUN /usr/local/bin/python -m pip install --upgrade pip

COPY requirements.txt /app

RUN pip install -U -r requirements.txt

COPY . /app

EXPOSE 5000 

ENTRYPOINT python admin
